[alias]
xtask = "run --package xtask --"

# For micro:bit v1.x

[target.thumbv6m-none-eabi]
runner = 'probe-rs run --chip nRF51822_xxAA'

# For micro:bit v2
[target.thumbv7em-none-eabi]
runner = "probe-rs run --chip nRF52833_xxAA"

[target.thumbv7em-none-eabihf]
runner = "probe-rs run --chip nRF52833_xxAA"

[env]
DEFMT_LOG = "trace"
